# Generated by Django 5.1.6 on 2025-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_rename_title_post_qq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='授課教師',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='開課名稱',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='開課單位',
        ),
        migrations.RemoveField(
            model_name='post',
            name='qq',
        ),
    ]
